= Analog Discovery 3 introduction

This repository includes a few tiny projects made to test some features of the Analog Discovery 3 (AD3). Those projects are introductions and may therefore include mistakes.

== Eye diagram

=== Introduction

The first feature offered by the AD3 I wanted to test was the eye diagram plots. The initial idea was to output a pseudo-random binary sequence using the AD3 waveform generator and loopback this signal back to the AD3 scope. A hardware low-pass filter was supposed to be inserted in between the AWG and the scope to change the binary signal's shape by changing the filter's cutoff frequency using a potentiometer.

But while setting up the waveform generation, I came accross the AD3 scripting capability and I wanted to try it out. I started writing a script that could generate a signal with random data, random noise, jitter and user-customizable transition time between two bits.

By using this script and changing the parameters, the user can see the impact of the parameters on the eye diagram.

=== Directory contents

The "Eye_Diagram" directory contains two files: the Waveforms workspace and a JavaScript file.

* Waveforms workspace: can be opened using the Waveforms software. It includes all that is needed to run this first test. The user must connect an AD3 to the computer and run the script included in the workspace. The script does the following:

. Check for a scope and a waveform to be opened.
. Configure the scope (this includes scales configuration, eye diagram, etc.).
. Create the signal that will be displayed on the eye diagram.
. Output the created signal on the waveform generator.
. Run the scope and waveform.

* JavaScript file: this file contains the script explained above. It is included in the workspace file but since the workspace file is not in a text format, I decided to include a copy of the file that can be viewed without the Waveforms software.

=== Improvements

This test could be improved by adding the low-pass filter with customizable cutoff frequency to dynamically change the eye's shape. It could be done in hardware, with a RC filter using a breadboard or with a digital filter. This could be done with a board such as the Eclypse Z7 board (FPGA board from Digilent with ADCs and DACs).

=== Known issues

The eye diagram data rate should be set to 5kHz by the script automatically but sometimes, it seems like the datarate is not set. Maybe this value is overwritten by something else after the script's execution.

== Logic Analyzer

=== Introduction

In a previous project, I worked with the Digilent's Eclypse Z7 development board using both the AWG and Digitizer Zmods extension modules.

An idea that was suggested to me was to use both the Eclypse Z7 and the AD3 by decoding the serial communication between the Eclypse Z7 and the Digitizer Zmod using the AD3 logic analyzer.

This was a bit tricky as I had to create a Vivado project to program the Eclypse Z7's Zynq FPGA and change I/O configurations made by the Digitizer Controller IP Core. The Vivado project is included in the repository.


=== Build the Vivado project

In order to build the project, the default design flow must not be used. Instead, follow the steps bellow:

. Open the project with Vivado 2021.2 (.xpr file).
. It may be needed to remove and add back the source files if Vivado tries to locate them using absolute paths (happens way too much when using Vivado on Windows).
. Run synthesis and wait for it to be finished.
. Execute the ChangeNetlist_Build.tcl (Tools > Run Tcl Scripts...).
. When the script is finished, the bitstream and the probes files should have been generated in the "Output_Files" directory.

=== View in Waveforms

(I do not know how the Waveforms workspace file will behave on someone else's computer but I have tried to open it from several directories on my computer and it does not seem to include things like absolute paths)

The Waveforms workspace (.dwf3work file) includes the custom decoder for the AD9648. The communication uses SPI (with one shared data signal, not MOSI/MISO) with a custom protocol to read/write from/to the device's registers.

The logic analyzer is therefore configured with two decoders: the SPI decoder that comes with Waveforms and a custom one, that translates the AD9648 specific protocol.

The JavaScript code of the decoder (and the value to text) is available in the "Custom Decoder" folder. But it is also included in the workspace file. The only reason why the JavaScript code is in the repository is for it to be easier to open and read (since the workspace file is not text-based, it is impossible to see the scripts in GitHub directly).

The workspace also remembers the last captured data so the communication can be analyzed even without the Eclypse Z7 board.